### PR TITLE
Make more prominent that only secrets are redacted

### PR DESCRIPTION
**Pull request by j-fuentes**

### CODE REVIEW

**Comment by charlieegan3** [comment]
/lgtm
/hold

One addition might be mentioning of managed fields. This is now removed from all resources but not really that interesting....

**Comment by j-fuentes** [comment]
> /lgtm
> /hold
> 
> One addition might be mentioning of managed fields. This is now removed from all resources but not really that interesting....

We redact both `managedFields` and `last-applied-configuration` but I am intentionally avoiding being too specific in this doc, as it is so easy to forget to update it if we change the code that filters fields.

**Comment by charlieegan3** [comment]
> intentionally avoiding being too specific
Makes sense

**Pull request merged**
