### PR TITLE
Remove missing pod rules

### PR DESCRIPTION
**Pull request by charlieegan3**
Needed after https://github.com/jetstack/preflight/pull/68

https://github.com/jetstack/preflight/issues/74 is a note about implementing these in the future so we don't forget them :smiley:

### CODE REVIEW

**Comment by j-fuentes** [comment]
Those rules are making use of the `manual` property. The problem is that is not really taken into account.

As an alternative to deleting them, I suggest that, at the moment, we omit the rules with `manual: true` when the reports are being created.

**Comment by charlieegan3** [comment]
Thanks for opening an issue for the manual rules. I think this is low priority but something we can keep in the backlog.

These are causing issues today as it's not something which is handled (hence the PR)

With #74 and #76 open to keep tabs on the issue, my feeling is that this can perhaps go in as is and we can return to the issue when (if) it's deemed a priority in the future?

**Comment by wwwil** [comment]
This PR I submitted should resolve this issue without needing to remove any rules: https://github.com/jetstack/preflight/pull/77

**Comment by charlieegan3** [comment]
I think https://github.com/jetstack/preflight/pull/77 does indeed fix this, so closing.

**Pull request closed without merging**
