### PR TITLE
Add Wil and Charlie to OWNERS

### PR DESCRIPTION
**Pull request by j-fuentes**
Signed-off-by: Jose Fuentes <jsfuentescastillo@gmail.com>

### CODE REVIEW

**Comment by charlieegan3** [comment]
Thanks Jose :+1:

**Comment by charlieegan3** [comment]
I guess this won't work til it's in master...

**Comment by charlieegan3** [comment]
Ahh cooooool. :shipit:

**Comment by j-fuentes** [comment]
> Ahh cooooool. :shipit:

It worked because if an owner's PRs can be lgtm'd by external people (I think).

**Pull request merged**
